[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
CPU = { path = "../CPU" }

sdl2 = "0.35.2"
rand = "0.8.4"

